# config.yaml
model: /gpfs/scratch/<project_id>/myfolder/hf_cache/models/models--mistralai--Mistral-Large-Instruct-2411/snapshots/ba78820945ae22361b0274cf0ae6d696c967c1a4
port: 8000
uvicorn-log-level: "info"
dtype: "bfloat16"
served-model-name: "Mistral-Large-Instruct-2411"
config_format: mistral
tokenizer-mode: mistral
load-format: mistral
tool-call-parser: mistral
enable-auto-tool-choice: true
tensor-parallel-size: 8
disable-log-requests: true
distributed-executor-backend: ray
enforce-eager: true
enable-chunked-prefill: true
cpu-offload-gb: 0.5