#!/bin/bash
#SBATCH --job-name=test_synth_gen
#SBATCH -D .
#SBATCH --output=slurm_out/mpi_%j.out
#SBATCH --error=slurm_out/mpi_%j.err
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=20
#SBATCH --time=00:15:00
#SBATCH --gres=gpu:1

export SRUN_CPUS_PER_TASK=${SLURM_CPUS_PER_TASK}
# Print some information about the job
echo "Job ID: $SLURM_JOB_ID"
echo "Node: $SLURMD_NODENAME"
echo "Timestamp: $(date)"

# Load any necessary modules
# Adjust these based on your HPC setup
module load singularity

# Set paths
CONTAINER_NAME="container.sif"


# Run the container with GPU access
echo "Running container with GPU access..."
singularity exec --nv ${CONTAINER_NAME} /bin/bash /gpfs/projects/<project_id>/myfolder/run.sh

echo "Job completed at $(date)"